apiVersion: v1
kind: ConfigMap
metadata:
  name: country-integration-config
data:
  DB_URL: "jdbc:mysql://192.168.100.7:3306/country_integration?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
  DB_USERNAME: "country_app"
  SOAP_COUNTRY_INFO_URL: "http://webservices.oorsprong.org/websamples.countryinfo/CountryInfoService.wso"
  SOAP_CONNECT_TIMEOUT: "5000"
  SOAP_REQUEST_TIMEOUT: "10000"