apiVersion: v1
kind: Service
metadata:
  name: country-integration
spec:
  type: NodePort
  selector:
    app: country-integration
  ports:
    - name: http
      port: 8085
      targetPort: http
      nodePort: 30085
      protocol: TCP
